// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#include <cstdbool>
#include <cstdint>

#include "flatbuffers/flatbuffers.h"
#include "objectbox.h"
#include "objectbox.hpp"


namespace NeuralStudio {
struct AnimationKeyframe_;

struct AnimationKeyframe {
    obx_id id;
    uint64_t object_id;
    std::string node_id;
    int64_t timestamp_ms;
    float pos_x;
    float pos_y;
    float pos_z;
    float rot_x;
    float rot_y;
    float rot_z;
    float scale_x;
    float scale_y;
    float scale_z;
    uint64_t script_id;
    std::string interpolation;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 2; }
    
        static void setObjectId(AnimationKeyframe& object, obx_id newId) { object.id = newId; }
    
        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const AnimationKeyframe& object);
    
        /// Read an object from a valid FlatBuffer
        static AnimationKeyframe fromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<AnimationKeyframe> newFromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, AnimationKeyframe& outObject);
    };
};

struct AnimationKeyframe_ {
    static const obx::Property<AnimationKeyframe, OBXPropertyType_Long> id;
    static const obx::Property<AnimationKeyframe, OBXPropertyType_Long> object_id;
    static const obx::Property<AnimationKeyframe, OBXPropertyType_String> node_id;
    static const obx::Property<AnimationKeyframe, OBXPropertyType_Date> timestamp_ms;
    static const obx::Property<AnimationKeyframe, OBXPropertyType_Float> pos_x;
    static const obx::Property<AnimationKeyframe, OBXPropertyType_Float> pos_y;
    static const obx::Property<AnimationKeyframe, OBXPropertyType_Float> pos_z;
    static const obx::Property<AnimationKeyframe, OBXPropertyType_Float> rot_x;
    static const obx::Property<AnimationKeyframe, OBXPropertyType_Float> rot_y;
    static const obx::Property<AnimationKeyframe, OBXPropertyType_Float> rot_z;
    static const obx::Property<AnimationKeyframe, OBXPropertyType_Float> scale_x;
    static const obx::Property<AnimationKeyframe, OBXPropertyType_Float> scale_y;
    static const obx::Property<AnimationKeyframe, OBXPropertyType_Float> scale_z;
    static const obx::Property<AnimationKeyframe, OBXPropertyType_Long> script_id;
    static const obx::Property<AnimationKeyframe, OBXPropertyType_String> interpolation;
};
}  // namespace NeuralStudio

