// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#include <cstdbool>
#include <cstdint>

#include "flatbuffers/flatbuffers.h"
#include "objectbox.h"
#include "objectbox.hpp"


namespace NeuralStudio {
struct BroadcastSettings_;

struct BroadcastSettings {
    obx_id id;
    std::string platform;
    std::string stream_key;
    std::string server_url;
    int32_t bitrate;
    std::string resolution;
    int32_t framerate;
    std::string encoder;
    int32_t audio_bitrate;
    int32_t sample_rate;
    bool enabled;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 1; }
    
        static void setObjectId(BroadcastSettings& object, obx_id newId) { object.id = newId; }
    
        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const BroadcastSettings& object);
    
        /// Read an object from a valid FlatBuffer
        static BroadcastSettings fromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<BroadcastSettings> newFromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, BroadcastSettings& outObject);
    };
};

struct BroadcastSettings_ {
    static const obx::Property<BroadcastSettings, OBXPropertyType_Long> id;
    static const obx::Property<BroadcastSettings, OBXPropertyType_String> platform;
    static const obx::Property<BroadcastSettings, OBXPropertyType_String> stream_key;
    static const obx::Property<BroadcastSettings, OBXPropertyType_String> server_url;
    static const obx::Property<BroadcastSettings, OBXPropertyType_Int> bitrate;
    static const obx::Property<BroadcastSettings, OBXPropertyType_String> resolution;
    static const obx::Property<BroadcastSettings, OBXPropertyType_Int> framerate;
    static const obx::Property<BroadcastSettings, OBXPropertyType_String> encoder;
    static const obx::Property<BroadcastSettings, OBXPropertyType_Int> audio_bitrate;
    static const obx::Property<BroadcastSettings, OBXPropertyType_Int> sample_rate;
    static const obx::Property<BroadcastSettings, OBXPropertyType_Bool> enabled;
};
}  // namespace NeuralStudio

