// Code generated by ObjectBox; DO NOT EDIT.

#include "GraphNode.obx.hpp"

const obx::Property<NeuralStudio::Profile::GraphNode, OBXPropertyType_Long> NeuralStudio::Profile::GraphNode_::id(1);
const obx::Property<NeuralStudio::Profile::GraphNode, OBXPropertyType_Long> NeuralStudio::Profile::GraphNode_::type_id(2);
const obx::Property<NeuralStudio::Profile::GraphNode, OBXPropertyType_String> NeuralStudio::Profile::GraphNode_::name(3);
const obx::Property<NeuralStudio::Profile::GraphNode, OBXPropertyType_Float> NeuralStudio::Profile::GraphNode_::pos_x(4);
const obx::Property<NeuralStudio::Profile::GraphNode, OBXPropertyType_Float> NeuralStudio::Profile::GraphNode_::pos_y(5);
const obx::Property<NeuralStudio::Profile::GraphNode, OBXPropertyType_Float> NeuralStudio::Profile::GraphNode_::pos_z(6);
const obx::Property<NeuralStudio::Profile::GraphNode, OBXPropertyType_String> NeuralStudio::Profile::GraphNode_::config_json(7);
const obx::Property<NeuralStudio::Profile::GraphNode, OBXPropertyType_Bool> NeuralStudio::Profile::GraphNode_::enabled(8);
const obx::Property<NeuralStudio::Profile::GraphNode, OBXPropertyType_Long> NeuralStudio::Profile::GraphNode_::created_at(9);

void NeuralStudio::Profile::GraphNode::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const NeuralStudio::Profile::GraphNode& object) {
    fbb.Clear();
    auto offsetname = fbb.CreateString(object.name);
    auto offsetconfig_json = fbb.CreateString(object.config_json);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddElement(6, object.type_id);
    fbb.AddOffset(8, offsetname);
    fbb.AddElement(10, object.pos_x);
    fbb.AddElement(12, object.pos_y);
    fbb.AddElement(14, object.pos_z);
    fbb.AddOffset(16, offsetconfig_json);
    fbb.AddElement(18, object.enabled ? 1 : 0);
    fbb.AddElement(20, object.created_at);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

NeuralStudio::Profile::GraphNode NeuralStudio::Profile::GraphNode::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    NeuralStudio::Profile::GraphNode object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<NeuralStudio::Profile::GraphNode> NeuralStudio::Profile::GraphNode::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<NeuralStudio::Profile::GraphNode>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void NeuralStudio::Profile::GraphNode::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, NeuralStudio::Profile::GraphNode& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    outObject.type_id = table->GetField<uint64_t>(6, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(8);
        if (ptr) {
            outObject.name.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.name.clear();
        }
    }
    outObject.pos_x = table->GetField<float>(10, 0.0f);
    outObject.pos_y = table->GetField<float>(12, 0.0f);
    outObject.pos_z = table->GetField<float>(14, 0.0f);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(16);
        if (ptr) {
            outObject.config_json.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.config_json.clear();
        }
    }
    outObject.enabled = table->GetField<uint8_t>(18, 0) != 0;
    outObject.created_at = table->GetField<int64_t>(20, 0);
}

