// Code generated by ObjectBox; DO NOT EDIT.

#include "GraphEdge.obx.hpp"

const obx::Property<NeuralStudio::Profile::GraphEdge, OBXPropertyType_Long> NeuralStudio::Profile::GraphEdge_::id(1);
const obx::RelationProperty<NeuralStudio::Profile::GraphEdge, GraphNode> NeuralStudio::Profile::GraphEdge_::from_node_id(2);
const obx::RelationProperty<NeuralStudio::Profile::GraphEdge, GraphNode> NeuralStudio::Profile::GraphEdge_::to_node_id(3);
const obx::Property<NeuralStudio::Profile::GraphEdge, OBXPropertyType_String> NeuralStudio::Profile::GraphEdge_::from_port(4);
const obx::Property<NeuralStudio::Profile::GraphEdge, OBXPropertyType_String> NeuralStudio::Profile::GraphEdge_::to_port(5);
const obx::Property<NeuralStudio::Profile::GraphEdge, OBXPropertyType_String> NeuralStudio::Profile::GraphEdge_::data_type(6);
const obx::Property<NeuralStudio::Profile::GraphEdge, OBXPropertyType_Bool> NeuralStudio::Profile::GraphEdge_::enabled(7);

void NeuralStudio::Profile::GraphEdge::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const NeuralStudio::Profile::GraphEdge& object) {
    fbb.Clear();
    auto offsetfrom_port = fbb.CreateString(object.from_port);
    auto offsetto_port = fbb.CreateString(object.to_port);
    auto offsetdata_type = fbb.CreateString(object.data_type);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddElement(6, object.from_node_id);
    fbb.AddElement(8, object.to_node_id);
    fbb.AddOffset(10, offsetfrom_port);
    fbb.AddOffset(12, offsetto_port);
    fbb.AddOffset(14, offsetdata_type);
    fbb.AddElement(16, object.enabled ? 1 : 0);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

NeuralStudio::Profile::GraphEdge NeuralStudio::Profile::GraphEdge::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    NeuralStudio::Profile::GraphEdge object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<NeuralStudio::Profile::GraphEdge> NeuralStudio::Profile::GraphEdge::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<NeuralStudio::Profile::GraphEdge>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void NeuralStudio::Profile::GraphEdge::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, NeuralStudio::Profile::GraphEdge& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    outObject.from_node_id = table->GetField<obx_id>(6, 0);
    outObject.to_node_id = table->GetField<obx_id>(8, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(10);
        if (ptr) {
            outObject.from_port.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.from_port.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(12);
        if (ptr) {
            outObject.to_port.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.to_port.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(14);
        if (ptr) {
            outObject.data_type.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.data_type.clear();
        }
    }
    outObject.enabled = table->GetField<uint8_t>(16, 0) != 0;
}

