// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#include <cstdbool>
#include <cstdint>

#include "flatbuffers/flatbuffers.h"
#include "objectbox.h"
#include "objectbox.hpp"

struct GraphNode; 

namespace NeuralStudio {
namespace Profile {
struct GraphEdge_;

struct GraphEdge {
    obx_id id;
    /// Source node ID
    obx_id from_node_id;
    /// Target node ID
    obx_id to_node_id;
    /// Source port name
    std::string from_port;
    /// Target port name
    std::string to_port;
    /// Data type flowing through
    std::string data_type;
    /// Connection enabled
    bool enabled;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 8; }
    
        static void setObjectId(GraphEdge& object, obx_id newId) { object.id = newId; }
    
        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const GraphEdge& object);
    
        /// Read an object from a valid FlatBuffer
        static GraphEdge fromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<GraphEdge> newFromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, GraphEdge& outObject);
    };
};

struct GraphEdge_ {
    static const obx::Property<GraphEdge, OBXPropertyType_Long> id;
    static const obx::RelationProperty<GraphEdge, GraphNode> from_node_id;
    static const obx::RelationProperty<GraphEdge, GraphNode> to_node_id;
    static const obx::Property<GraphEdge, OBXPropertyType_String> from_port;
    static const obx::Property<GraphEdge, OBXPropertyType_String> to_port;
    static const obx::Property<GraphEdge, OBXPropertyType_String> data_type;
    static const obx::Property<GraphEdge, OBXPropertyType_Bool> enabled;
};
}  // namespace Profile
}  // namespace NeuralStudio

