// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#include <cstdbool>
#include <cstdint>

#include "flatbuffers/flatbuffers.h"
#include "objectbox.h"
#include "objectbox.hpp"


namespace NeuralStudio {
namespace Profile {
struct GraphNode_;

struct GraphNode {
    obx_id id;
    /// Reference to Master NodeType
    uint64_t type_id;
    /// User-assigned name
    std::string name;
    /// Blueprint canvas position
    float pos_x;
    float pos_y;
    float pos_z;
    /// User configuration (JSON, overrides defaults)
    std::string config_json;
    /// Execution enabled
    bool enabled;
    int64_t created_at;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 7; }
    
        static void setObjectId(GraphNode& object, obx_id newId) { object.id = newId; }
    
        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const GraphNode& object);
    
        /// Read an object from a valid FlatBuffer
        static GraphNode fromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<GraphNode> newFromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, GraphNode& outObject);
    };
};

struct GraphNode_ {
    static const obx::Property<GraphNode, OBXPropertyType_Long> id;
    static const obx::Property<GraphNode, OBXPropertyType_Long> type_id;
    static const obx::Property<GraphNode, OBXPropertyType_String> name;
    static const obx::Property<GraphNode, OBXPropertyType_Float> pos_x;
    static const obx::Property<GraphNode, OBXPropertyType_Float> pos_y;
    static const obx::Property<GraphNode, OBXPropertyType_Float> pos_z;
    static const obx::Property<GraphNode, OBXPropertyType_String> config_json;
    static const obx::Property<GraphNode, OBXPropertyType_Bool> enabled;
    static const obx::Property<GraphNode, OBXPropertyType_Long> created_at;
};
}  // namespace Profile
}  // namespace NeuralStudio

