// Code generated by ObjectBox; DO NOT EDIT.

#include "SceneObject.obx.hpp"

const obx::Property<NeuralStudio::SceneObject, OBXPropertyType_Long> NeuralStudio::SceneObject_::id(1);
const obx::Property<NeuralStudio::SceneObject, OBXPropertyType_String> NeuralStudio::SceneObject_::node_id(2);
const obx::Property<NeuralStudio::SceneObject, OBXPropertyType_String> NeuralStudio::SceneObject_::type(3);
const obx::Property<NeuralStudio::SceneObject, OBXPropertyType_String> NeuralStudio::SceneObject_::name(4);
const obx::Property<NeuralStudio::SceneObject, OBXPropertyType_Float> NeuralStudio::SceneObject_::pos_x(5);
const obx::Property<NeuralStudio::SceneObject, OBXPropertyType_Float> NeuralStudio::SceneObject_::pos_y(6);
const obx::Property<NeuralStudio::SceneObject, OBXPropertyType_Float> NeuralStudio::SceneObject_::pos_z(7);
const obx::Property<NeuralStudio::SceneObject, OBXPropertyType_Float> NeuralStudio::SceneObject_::rot_x(8);
const obx::Property<NeuralStudio::SceneObject, OBXPropertyType_Float> NeuralStudio::SceneObject_::rot_y(9);
const obx::Property<NeuralStudio::SceneObject, OBXPropertyType_Float> NeuralStudio::SceneObject_::rot_z(10);
const obx::Property<NeuralStudio::SceneObject, OBXPropertyType_Float> NeuralStudio::SceneObject_::scale_x(11);
const obx::Property<NeuralStudio::SceneObject, OBXPropertyType_Float> NeuralStudio::SceneObject_::scale_y(12);
const obx::Property<NeuralStudio::SceneObject, OBXPropertyType_Float> NeuralStudio::SceneObject_::scale_z(13);
const obx::Property<NeuralStudio::SceneObject, OBXPropertyType_Bool> NeuralStudio::SceneObject_::enabled(14);
const obx::Property<NeuralStudio::SceneObject, OBXPropertyType_String> NeuralStudio::SceneObject_::properties(15);

void NeuralStudio::SceneObject::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const NeuralStudio::SceneObject& object) {
    fbb.Clear();
    auto offsetnode_id = fbb.CreateString(object.node_id);
    auto offsettype = fbb.CreateString(object.type);
    auto offsetname = fbb.CreateString(object.name);
    auto offsetproperties = fbb.CreateString(object.properties);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddOffset(6, offsetnode_id);
    fbb.AddOffset(8, offsettype);
    fbb.AddOffset(10, offsetname);
    fbb.AddElement(12, object.pos_x);
    fbb.AddElement(14, object.pos_y);
    fbb.AddElement(16, object.pos_z);
    fbb.AddElement(18, object.rot_x);
    fbb.AddElement(20, object.rot_y);
    fbb.AddElement(22, object.rot_z);
    fbb.AddElement(24, object.scale_x);
    fbb.AddElement(26, object.scale_y);
    fbb.AddElement(28, object.scale_z);
    fbb.AddElement(30, object.enabled ? 1 : 0);
    fbb.AddOffset(32, offsetproperties);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

NeuralStudio::SceneObject NeuralStudio::SceneObject::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    NeuralStudio::SceneObject object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<NeuralStudio::SceneObject> NeuralStudio::SceneObject::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<NeuralStudio::SceneObject>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void NeuralStudio::SceneObject::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, NeuralStudio::SceneObject& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(6);
        if (ptr) {
            outObject.node_id.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.node_id.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(8);
        if (ptr) {
            outObject.type.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.type.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(10);
        if (ptr) {
            outObject.name.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.name.clear();
        }
    }
    outObject.pos_x = table->GetField<float>(12, 0.0f);
    outObject.pos_y = table->GetField<float>(14, 0.0f);
    outObject.pos_z = table->GetField<float>(16, 0.0f);
    outObject.rot_x = table->GetField<float>(18, 0.0f);
    outObject.rot_y = table->GetField<float>(20, 0.0f);
    outObject.rot_z = table->GetField<float>(22, 0.0f);
    outObject.scale_x = table->GetField<float>(24, 0.0f);
    outObject.scale_y = table->GetField<float>(26, 0.0f);
    outObject.scale_z = table->GetField<float>(28, 0.0f);
    outObject.enabled = table->GetField<uint8_t>(30, 0) != 0;
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(32);
        if (ptr) {
            outObject.properties.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.properties.clear();
        }
    }
}

