// Code generated by ObjectBox; DO NOT EDIT.

#include "ConnectionRule.obx.hpp"

const obx::Property<NeuralStudio::Master::ConnectionRule, OBXPropertyType_Long> NeuralStudio::Master::ConnectionRule_::id(1);
const obx::Property<NeuralStudio::Master::ConnectionRule, OBXPropertyType_Long> NeuralStudio::Master::ConnectionRule_::from_type_id(2);
const obx::Property<NeuralStudio::Master::ConnectionRule, OBXPropertyType_Long> NeuralStudio::Master::ConnectionRule_::to_type_id(3);
const obx::Property<NeuralStudio::Master::ConnectionRule, OBXPropertyType_String> NeuralStudio::Master::ConnectionRule_::from_port_name(4);
const obx::Property<NeuralStudio::Master::ConnectionRule, OBXPropertyType_String> NeuralStudio::Master::ConnectionRule_::to_port_name(5);
const obx::Property<NeuralStudio::Master::ConnectionRule, OBXPropertyType_String> NeuralStudio::Master::ConnectionRule_::constraints(6);

void NeuralStudio::Master::ConnectionRule::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const NeuralStudio::Master::ConnectionRule& object) {
    fbb.Clear();
    auto offsetfrom_port_name = fbb.CreateString(object.from_port_name);
    auto offsetto_port_name = fbb.CreateString(object.to_port_name);
    auto offsetconstraints = fbb.CreateString(object.constraints);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddElement(6, object.from_type_id);
    fbb.AddElement(8, object.to_type_id);
    fbb.AddOffset(10, offsetfrom_port_name);
    fbb.AddOffset(12, offsetto_port_name);
    fbb.AddOffset(14, offsetconstraints);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

NeuralStudio::Master::ConnectionRule NeuralStudio::Master::ConnectionRule::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    NeuralStudio::Master::ConnectionRule object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<NeuralStudio::Master::ConnectionRule> NeuralStudio::Master::ConnectionRule::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<NeuralStudio::Master::ConnectionRule>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void NeuralStudio::Master::ConnectionRule::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, NeuralStudio::Master::ConnectionRule& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    outObject.from_type_id = table->GetField<uint64_t>(6, 0);
    outObject.to_type_id = table->GetField<uint64_t>(8, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(10);
        if (ptr) {
            outObject.from_port_name.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.from_port_name.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(12);
        if (ptr) {
            outObject.to_port_name.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.to_port_name.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(14);
        if (ptr) {
            outObject.constraints.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.constraints.clear();
        }
    }
}

