// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#include <cstdbool>
#include <cstdint>

#include "flatbuffers/flatbuffers.h"
#include "objectbox.h"
#include "objectbox.hpp"


namespace NeuralStudio {
namespace Master {
struct ConnectionRule_;

struct ConnectionRule {
    obx_id id;
    /// Source node type ID
    uint64_t from_type_id;
    /// Target node type ID
    uint64_t to_type_id;
    /// Source port name
    std::string from_port_name;
    /// Target port name
    std::string to_port_name;
    /// Validation constraints (JSON)
    std::string constraints;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 5; }
    
        static void setObjectId(ConnectionRule& object, obx_id newId) { object.id = newId; }
    
        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const ConnectionRule& object);
    
        /// Read an object from a valid FlatBuffer
        static ConnectionRule fromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<ConnectionRule> newFromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, ConnectionRule& outObject);
    };
};

struct ConnectionRule_ {
    static const obx::Property<ConnectionRule, OBXPropertyType_Long> id;
    static const obx::Property<ConnectionRule, OBXPropertyType_Long> from_type_id;
    static const obx::Property<ConnectionRule, OBXPropertyType_Long> to_type_id;
    static const obx::Property<ConnectionRule, OBXPropertyType_String> from_port_name;
    static const obx::Property<ConnectionRule, OBXPropertyType_String> to_port_name;
    static const obx::Property<ConnectionRule, OBXPropertyType_String> constraints;
};
}  // namespace Master
}  // namespace NeuralStudio

