// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#include <cstdbool>
#include <cstdint>

#include "flatbuffers/flatbuffers.h"
#include "objectbox.h"
#include "objectbox.hpp"


namespace NeuralStudio {
namespace Master {
struct NodeType_;

struct NodeType {
    obx_id id;
    /// Internal type identifier
    std::string name;
    /// User-facing category
    std::string category;
    /// Display name
    std::string display_name;
    /// Description for tooltips
    std::string description;
    /// Material icon name
    std::string icon;
    /// Default configuration (JSON)
    std::string default_config;
    /// Input port definitions (JSON array)
    std::string input_ports;
    /// Output port definitions (JSON array)
    std::string output_ports;
    /// Schema version
    int32_t version;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 4; }
    
        static void setObjectId(NodeType& object, obx_id newId) { object.id = newId; }
    
        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const NodeType& object);
    
        /// Read an object from a valid FlatBuffer
        static NodeType fromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<NodeType> newFromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, NodeType& outObject);
    };
};

struct NodeType_ {
    static const obx::Property<NodeType, OBXPropertyType_Long> id;
    static const obx::Property<NodeType, OBXPropertyType_String> name;
    static const obx::Property<NodeType, OBXPropertyType_String> category;
    static const obx::Property<NodeType, OBXPropertyType_String> display_name;
    static const obx::Property<NodeType, OBXPropertyType_String> description;
    static const obx::Property<NodeType, OBXPropertyType_String> icon;
    static const obx::Property<NodeType, OBXPropertyType_String> default_config;
    static const obx::Property<NodeType, OBXPropertyType_String> input_ports;
    static const obx::Property<NodeType, OBXPropertyType_String> output_ports;
    static const obx::Property<NodeType, OBXPropertyType_Int> version;
};
}  // namespace Master
}  // namespace NeuralStudio

