// Code generated by ObjectBox; DO NOT EDIT.

#include "NodeType.obx.hpp"

const obx::Property<NeuralStudio::Master::NodeType, OBXPropertyType_Long> NeuralStudio::Master::NodeType_::id(1);
const obx::Property<NeuralStudio::Master::NodeType, OBXPropertyType_String> NeuralStudio::Master::NodeType_::name(2);
const obx::Property<NeuralStudio::Master::NodeType, OBXPropertyType_String> NeuralStudio::Master::NodeType_::category(3);
const obx::Property<NeuralStudio::Master::NodeType, OBXPropertyType_String> NeuralStudio::Master::NodeType_::display_name(4);
const obx::Property<NeuralStudio::Master::NodeType, OBXPropertyType_String> NeuralStudio::Master::NodeType_::description(5);
const obx::Property<NeuralStudio::Master::NodeType, OBXPropertyType_String> NeuralStudio::Master::NodeType_::icon(6);
const obx::Property<NeuralStudio::Master::NodeType, OBXPropertyType_String> NeuralStudio::Master::NodeType_::default_config(7);
const obx::Property<NeuralStudio::Master::NodeType, OBXPropertyType_String> NeuralStudio::Master::NodeType_::input_ports(8);
const obx::Property<NeuralStudio::Master::NodeType, OBXPropertyType_String> NeuralStudio::Master::NodeType_::output_ports(9);
const obx::Property<NeuralStudio::Master::NodeType, OBXPropertyType_Int> NeuralStudio::Master::NodeType_::version(10);

void NeuralStudio::Master::NodeType::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const NeuralStudio::Master::NodeType& object) {
    fbb.Clear();
    auto offsetname = fbb.CreateString(object.name);
    auto offsetcategory = fbb.CreateString(object.category);
    auto offsetdisplay_name = fbb.CreateString(object.display_name);
    auto offsetdescription = fbb.CreateString(object.description);
    auto offseticon = fbb.CreateString(object.icon);
    auto offsetdefault_config = fbb.CreateString(object.default_config);
    auto offsetinput_ports = fbb.CreateString(object.input_ports);
    auto offsetoutput_ports = fbb.CreateString(object.output_ports);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddOffset(6, offsetname);
    fbb.AddOffset(8, offsetcategory);
    fbb.AddOffset(10, offsetdisplay_name);
    fbb.AddOffset(12, offsetdescription);
    fbb.AddOffset(14, offseticon);
    fbb.AddOffset(16, offsetdefault_config);
    fbb.AddOffset(18, offsetinput_ports);
    fbb.AddOffset(20, offsetoutput_ports);
    fbb.AddElement(22, object.version);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

NeuralStudio::Master::NodeType NeuralStudio::Master::NodeType::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    NeuralStudio::Master::NodeType object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<NeuralStudio::Master::NodeType> NeuralStudio::Master::NodeType::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<NeuralStudio::Master::NodeType>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void NeuralStudio::Master::NodeType::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, NeuralStudio::Master::NodeType& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(6);
        if (ptr) {
            outObject.name.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.name.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(8);
        if (ptr) {
            outObject.category.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.category.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(10);
        if (ptr) {
            outObject.display_name.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.display_name.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(12);
        if (ptr) {
            outObject.description.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.description.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(14);
        if (ptr) {
            outObject.icon.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.icon.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(16);
        if (ptr) {
            outObject.default_config.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.default_config.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(18);
        if (ptr) {
            outObject.input_ports.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.input_ports.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(20);
        if (ptr) {
            outObject.output_ports.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.output_ports.clear();
        }
    }
    outObject.version = table->GetField<int32_t>(22, 0);
}

