// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#include <cstdbool>
#include <cstdint>

#include "flatbuffers/flatbuffers.h"
#include "objectbox.h"
#include "objectbox.hpp"


namespace NeuralStudio {
namespace Master {
struct PipelineTemplate_;

struct PipelineTemplate {
    obx_id id;
    /// Template name
    std::string name;
    /// Category
    std::string category;
    /// Description
    std::string description;
    /// Serialized graph (JSON)
    std::string graph_json;
    /// Thumbnail path
    std::string thumbnail;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 6; }
    
        static void setObjectId(PipelineTemplate& object, obx_id newId) { object.id = newId; }
    
        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const PipelineTemplate& object);
    
        /// Read an object from a valid FlatBuffer
        static PipelineTemplate fromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<PipelineTemplate> newFromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, PipelineTemplate& outObject);
    };
};

struct PipelineTemplate_ {
    static const obx::Property<PipelineTemplate, OBXPropertyType_Long> id;
    static const obx::Property<PipelineTemplate, OBXPropertyType_String> name;
    static const obx::Property<PipelineTemplate, OBXPropertyType_String> category;
    static const obx::Property<PipelineTemplate, OBXPropertyType_String> description;
    static const obx::Property<PipelineTemplate, OBXPropertyType_String> graph_json;
    static const obx::Property<PipelineTemplate, OBXPropertyType_String> thumbnail;
};
}  // namespace Master
}  // namespace NeuralStudio

