// Code generated by ObjectBox; DO NOT EDIT.

#include "PipelineTemplate.obx.hpp"

const obx::Property<NeuralStudio::Master::PipelineTemplate, OBXPropertyType_Long> NeuralStudio::Master::PipelineTemplate_::id(1);
const obx::Property<NeuralStudio::Master::PipelineTemplate, OBXPropertyType_String> NeuralStudio::Master::PipelineTemplate_::name(2);
const obx::Property<NeuralStudio::Master::PipelineTemplate, OBXPropertyType_String> NeuralStudio::Master::PipelineTemplate_::category(3);
const obx::Property<NeuralStudio::Master::PipelineTemplate, OBXPropertyType_String> NeuralStudio::Master::PipelineTemplate_::description(4);
const obx::Property<NeuralStudio::Master::PipelineTemplate, OBXPropertyType_String> NeuralStudio::Master::PipelineTemplate_::graph_json(5);
const obx::Property<NeuralStudio::Master::PipelineTemplate, OBXPropertyType_String> NeuralStudio::Master::PipelineTemplate_::thumbnail(6);

void NeuralStudio::Master::PipelineTemplate::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const NeuralStudio::Master::PipelineTemplate& object) {
    fbb.Clear();
    auto offsetname = fbb.CreateString(object.name);
    auto offsetcategory = fbb.CreateString(object.category);
    auto offsetdescription = fbb.CreateString(object.description);
    auto offsetgraph_json = fbb.CreateString(object.graph_json);
    auto offsetthumbnail = fbb.CreateString(object.thumbnail);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddOffset(6, offsetname);
    fbb.AddOffset(8, offsetcategory);
    fbb.AddOffset(10, offsetdescription);
    fbb.AddOffset(12, offsetgraph_json);
    fbb.AddOffset(14, offsetthumbnail);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

NeuralStudio::Master::PipelineTemplate NeuralStudio::Master::PipelineTemplate::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    NeuralStudio::Master::PipelineTemplate object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<NeuralStudio::Master::PipelineTemplate> NeuralStudio::Master::PipelineTemplate::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<NeuralStudio::Master::PipelineTemplate>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void NeuralStudio::Master::PipelineTemplate::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, NeuralStudio::Master::PipelineTemplate& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(6);
        if (ptr) {
            outObject.name.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.name.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(8);
        if (ptr) {
            outObject.category.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.category.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(10);
        if (ptr) {
            outObject.description.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.description.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(12);
        if (ptr) {
            outObject.graph_json.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.graph_json.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(14);
        if (ptr) {
            outObject.thumbnail.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.thumbnail.clear();
        }
    }
}

