// Code generated by ObjectBox; DO NOT EDIT.

#include "GraphEvent.obx.hpp"

const obx::Property<NeuralStudio::AI::GraphEvent, OBXPropertyType_Long> NeuralStudio::AI::GraphEvent_::id(1);
const obx::Property<NeuralStudio::AI::GraphEvent, OBXPropertyType_Date> NeuralStudio::AI::GraphEvent_::timestamp(2);
const obx::Property<NeuralStudio::AI::GraphEvent, OBXPropertyType_String> NeuralStudio::AI::GraphEvent_::event_type(3);
const obx::Property<NeuralStudio::AI::GraphEvent, OBXPropertyType_String> NeuralStudio::AI::GraphEvent_::node_type(4);
const obx::Property<NeuralStudio::AI::GraphEvent, OBXPropertyType_String> NeuralStudio::AI::GraphEvent_::from_type(5);
const obx::Property<NeuralStudio::AI::GraphEvent, OBXPropertyType_String> NeuralStudio::AI::GraphEvent_::to_type(6);
const obx::Property<NeuralStudio::AI::GraphEvent, OBXPropertyType_String> NeuralStudio::AI::GraphEvent_::from_port(7);
const obx::Property<NeuralStudio::AI::GraphEvent, OBXPropertyType_String> NeuralStudio::AI::GraphEvent_::to_port(8);
const obx::Property<NeuralStudio::AI::GraphEvent, OBXPropertyType_String> NeuralStudio::AI::GraphEvent_::context_hash(9);
const obx::Property<NeuralStudio::AI::GraphEvent, OBXPropertyType_String> NeuralStudio::AI::GraphEvent_::session_id(10);

void NeuralStudio::AI::GraphEvent::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const NeuralStudio::AI::GraphEvent& object) {
    fbb.Clear();
    auto offsetevent_type = fbb.CreateString(object.event_type);
    auto offsetnode_type = fbb.CreateString(object.node_type);
    auto offsetfrom_type = fbb.CreateString(object.from_type);
    auto offsetto_type = fbb.CreateString(object.to_type);
    auto offsetfrom_port = fbb.CreateString(object.from_port);
    auto offsetto_port = fbb.CreateString(object.to_port);
    auto offsetcontext_hash = fbb.CreateString(object.context_hash);
    auto offsetsession_id = fbb.CreateString(object.session_id);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddElement(6, object.timestamp);
    fbb.AddOffset(8, offsetevent_type);
    fbb.AddOffset(10, offsetnode_type);
    fbb.AddOffset(12, offsetfrom_type);
    fbb.AddOffset(14, offsetto_type);
    fbb.AddOffset(16, offsetfrom_port);
    fbb.AddOffset(18, offsetto_port);
    fbb.AddOffset(20, offsetcontext_hash);
    fbb.AddOffset(22, offsetsession_id);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

NeuralStudio::AI::GraphEvent NeuralStudio::AI::GraphEvent::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    NeuralStudio::AI::GraphEvent object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<NeuralStudio::AI::GraphEvent> NeuralStudio::AI::GraphEvent::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<NeuralStudio::AI::GraphEvent>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void NeuralStudio::AI::GraphEvent::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, NeuralStudio::AI::GraphEvent& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    outObject.timestamp = table->GetField<int64_t>(6, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(8);
        if (ptr) {
            outObject.event_type.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.event_type.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(10);
        if (ptr) {
            outObject.node_type.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.node_type.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(12);
        if (ptr) {
            outObject.from_type.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.from_type.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(14);
        if (ptr) {
            outObject.to_type.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.to_type.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(16);
        if (ptr) {
            outObject.from_port.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.from_port.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(18);
        if (ptr) {
            outObject.to_port.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.to_port.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(20);
        if (ptr) {
            outObject.context_hash.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.context_hash.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(22);
        if (ptr) {
            outObject.session_id.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.session_id.clear();
        }
    }
}

