// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#include <cstdbool>
#include <cstdint>

#include "flatbuffers/flatbuffers.h"
#include "objectbox.h"
#include "objectbox.hpp"


namespace NeuralStudio {
namespace AI {
struct GraphEvent_;

struct GraphEvent {
    obx_id id;
    int64_t timestamp;
    /// Event type: "node_add", "node_delete", "edge_create", "edge_delete"
    std::string event_type;
    /// Node type involved
    std::string node_type;
    /// For connection events
    std::string from_type;
    std::string to_type;
    std::string from_port;
    std::string to_port;
    /// Graph state before event
    std::string context_hash;
    /// Session identifier
    std::string session_id;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 9; }
    
        static void setObjectId(GraphEvent& object, obx_id newId) { object.id = newId; }
    
        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const GraphEvent& object);
    
        /// Read an object from a valid FlatBuffer
        static GraphEvent fromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<GraphEvent> newFromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, GraphEvent& outObject);
    };
};

struct GraphEvent_ {
    static const obx::Property<GraphEvent, OBXPropertyType_Long> id;
    static const obx::Property<GraphEvent, OBXPropertyType_Date> timestamp;
    static const obx::Property<GraphEvent, OBXPropertyType_String> event_type;
    static const obx::Property<GraphEvent, OBXPropertyType_String> node_type;
    static const obx::Property<GraphEvent, OBXPropertyType_String> from_type;
    static const obx::Property<GraphEvent, OBXPropertyType_String> to_type;
    static const obx::Property<GraphEvent, OBXPropertyType_String> from_port;
    static const obx::Property<GraphEvent, OBXPropertyType_String> to_port;
    static const obx::Property<GraphEvent, OBXPropertyType_String> context_hash;
    static const obx::Property<GraphEvent, OBXPropertyType_String> session_id;
};
}  // namespace AI
}  // namespace NeuralStudio

