// Code generated by ObjectBox; DO NOT EDIT.

#include "GraphPattern.obx.hpp"

const obx::Property<NeuralStudio::AI::GraphPattern, OBXPropertyType_Long> NeuralStudio::AI::GraphPattern_::id(1);
const obx::Property<NeuralStudio::AI::GraphPattern, OBXPropertyType_String> NeuralStudio::AI::GraphPattern_::pattern_hash(2);
const obx::Property<NeuralStudio::AI::GraphPattern, OBXPropertyType_String> NeuralStudio::AI::GraphPattern_::node_sequence(3);
const obx::Property<NeuralStudio::AI::GraphPattern, OBXPropertyType_String> NeuralStudio::AI::GraphPattern_::edge_structure(4);
const obx::Property<NeuralStudio::AI::GraphPattern, OBXPropertyType_Long> NeuralStudio::AI::GraphPattern_::frequency(5);
const obx::Property<NeuralStudio::AI::GraphPattern, OBXPropertyType_Float> NeuralStudio::AI::GraphPattern_::success_rate(6);
const obx::Property<NeuralStudio::AI::GraphPattern, OBXPropertyType_Long> NeuralStudio::AI::GraphPattern_::last_updated(7);

void NeuralStudio::AI::GraphPattern::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const NeuralStudio::AI::GraphPattern& object) {
    fbb.Clear();
    auto offsetpattern_hash = fbb.CreateString(object.pattern_hash);
    auto offsetnode_sequence = fbb.CreateString(object.node_sequence);
    auto offsetedge_structure = fbb.CreateString(object.edge_structure);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddOffset(6, offsetpattern_hash);
    fbb.AddOffset(8, offsetnode_sequence);
    fbb.AddOffset(10, offsetedge_structure);
    fbb.AddElement(12, object.frequency);
    fbb.AddElement(14, object.success_rate);
    fbb.AddElement(16, object.last_updated);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

NeuralStudio::AI::GraphPattern NeuralStudio::AI::GraphPattern::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    NeuralStudio::AI::GraphPattern object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<NeuralStudio::AI::GraphPattern> NeuralStudio::AI::GraphPattern::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<NeuralStudio::AI::GraphPattern>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void NeuralStudio::AI::GraphPattern::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, NeuralStudio::AI::GraphPattern& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(6);
        if (ptr) {
            outObject.pattern_hash.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.pattern_hash.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(8);
        if (ptr) {
            outObject.node_sequence.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.node_sequence.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(10);
        if (ptr) {
            outObject.edge_structure.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.edge_structure.clear();
        }
    }
    outObject.frequency = table->GetField<uint64_t>(12, 0);
    outObject.success_rate = table->GetField<float>(14, 0.0f);
    outObject.last_updated = table->GetField<int64_t>(16, 0);
}

