// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#include <cstdbool>
#include <cstdint>

#include "flatbuffers/flatbuffers.h"
#include "objectbox.h"
#include "objectbox.hpp"


namespace NeuralStudio {
namespace AI {
struct GraphPattern_;

struct GraphPattern {
    obx_id id;
    /// Canonical graph hash
    std::string pattern_hash;
    /// Node type sequence (canonical order)
    std::string node_sequence;
    /// Edge structure (canonical)
    std::string edge_structure;
    /// Occurrence frequency
    uint64_t frequency;
    /// Success rate (0.0 - 1.0)
    float success_rate;
    /// Last observation timestamp
    int64_t last_updated;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 10; }
    
        static void setObjectId(GraphPattern& object, obx_id newId) { object.id = newId; }
    
        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const GraphPattern& object);
    
        /// Read an object from a valid FlatBuffer
        static GraphPattern fromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<GraphPattern> newFromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, GraphPattern& outObject);
    };
};

struct GraphPattern_ {
    static const obx::Property<GraphPattern, OBXPropertyType_Long> id;
    static const obx::Property<GraphPattern, OBXPropertyType_String> pattern_hash;
    static const obx::Property<GraphPattern, OBXPropertyType_String> node_sequence;
    static const obx::Property<GraphPattern, OBXPropertyType_String> edge_structure;
    static const obx::Property<GraphPattern, OBXPropertyType_Long> frequency;
    static const obx::Property<GraphPattern, OBXPropertyType_Float> success_rate;
    static const obx::Property<GraphPattern, OBXPropertyType_Long> last_updated;
};
}  // namespace AI
}  // namespace NeuralStudio

