// Code generated by ObjectBox; DO NOT EDIT.

#include "IntentPrediction.obx.hpp"

const obx::Property<NeuralStudio::AI::IntentPrediction, OBXPropertyType_Long> NeuralStudio::AI::IntentPrediction_::id(1);
const obx::Property<NeuralStudio::AI::IntentPrediction, OBXPropertyType_String> NeuralStudio::AI::IntentPrediction_::context_hash(2);
const obx::Property<NeuralStudio::AI::IntentPrediction, OBXPropertyType_String> NeuralStudio::AI::IntentPrediction_::predicted_node_type(3);
const obx::Property<NeuralStudio::AI::IntentPrediction, OBXPropertyType_String> NeuralStudio::AI::IntentPrediction_::predicted_from_type(4);
const obx::Property<NeuralStudio::AI::IntentPrediction, OBXPropertyType_String> NeuralStudio::AI::IntentPrediction_::predicted_to_type(5);
const obx::Property<NeuralStudio::AI::IntentPrediction, OBXPropertyType_Float> NeuralStudio::AI::IntentPrediction_::confidence(6);
const obx::Property<NeuralStudio::AI::IntentPrediction, OBXPropertyType_String> NeuralStudio::AI::IntentPrediction_::reason(7);

void NeuralStudio::AI::IntentPrediction::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const NeuralStudio::AI::IntentPrediction& object) {
    fbb.Clear();
    auto offsetcontext_hash = fbb.CreateString(object.context_hash);
    auto offsetpredicted_node_type = fbb.CreateString(object.predicted_node_type);
    auto offsetpredicted_from_type = fbb.CreateString(object.predicted_from_type);
    auto offsetpredicted_to_type = fbb.CreateString(object.predicted_to_type);
    auto offsetreason = fbb.CreateString(object.reason);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddOffset(6, offsetcontext_hash);
    fbb.AddOffset(8, offsetpredicted_node_type);
    fbb.AddOffset(10, offsetpredicted_from_type);
    fbb.AddOffset(12, offsetpredicted_to_type);
    fbb.AddElement(14, object.confidence);
    fbb.AddOffset(16, offsetreason);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

NeuralStudio::AI::IntentPrediction NeuralStudio::AI::IntentPrediction::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    NeuralStudio::AI::IntentPrediction object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<NeuralStudio::AI::IntentPrediction> NeuralStudio::AI::IntentPrediction::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<NeuralStudio::AI::IntentPrediction>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void NeuralStudio::AI::IntentPrediction::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, NeuralStudio::AI::IntentPrediction& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(6);
        if (ptr) {
            outObject.context_hash.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.context_hash.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(8);
        if (ptr) {
            outObject.predicted_node_type.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.predicted_node_type.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(10);
        if (ptr) {
            outObject.predicted_from_type.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.predicted_from_type.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(12);
        if (ptr) {
            outObject.predicted_to_type.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.predicted_to_type.clear();
        }
    }
    outObject.confidence = table->GetField<float>(14, 0.0f);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(16);
        if (ptr) {
            outObject.reason.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.reason.clear();
        }
    }
}

