// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#include <cstdbool>
#include <cstdint>

#include "flatbuffers/flatbuffers.h"
#include "objectbox.h"
#include "objectbox.hpp"


namespace NeuralStudio {
namespace AI {
struct IntentPrediction_;

struct IntentPrediction {
    obx_id id;
    /// Current graph context hash
    std::string context_hash;
    /// Predicted next node type
    std::string predicted_node_type;
    /// Predicted connection source
    std::string predicted_from_type;
    /// Predicted connection target
    std::string predicted_to_type;
    /// Confidence score (0.0 - 1.0)
    float confidence;
    /// Reasoning explanation
    std::string reason;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 11; }
    
        static void setObjectId(IntentPrediction& object, obx_id newId) { object.id = newId; }
    
        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const IntentPrediction& object);
    
        /// Read an object from a valid FlatBuffer
        static IntentPrediction fromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<IntentPrediction> newFromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, IntentPrediction& outObject);
    };
};

struct IntentPrediction_ {
    static const obx::Property<IntentPrediction, OBXPropertyType_Long> id;
    static const obx::Property<IntentPrediction, OBXPropertyType_String> context_hash;
    static const obx::Property<IntentPrediction, OBXPropertyType_String> predicted_node_type;
    static const obx::Property<IntentPrediction, OBXPropertyType_String> predicted_from_type;
    static const obx::Property<IntentPrediction, OBXPropertyType_String> predicted_to_type;
    static const obx::Property<IntentPrediction, OBXPropertyType_Float> confidence;
    static const obx::Property<IntentPrediction, OBXPropertyType_String> reason;
};
}  // namespace AI
}  // namespace NeuralStudio

