// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#ifdef __cplusplus
#include <cstdbool>
#include <cstdint>
extern "C" {
#else
#include <stdbool.h>
#include <stdint.h>
#endif
#include "objectbox.h"

/// Initializes an ObjectBox model for all entities. 
/// The returned pointer may be NULL if the allocation failed. If the returned model is not NULL, you should check if   
/// any error occurred by calling obx_model_error_code() and/or obx_model_error_message(). If an error occurred, you're
/// responsible for freeing the resources by calling obx_model_free().
/// In case there was no error when setting the model up (i.e. obx_model_error_code() returned 0), you may configure 
/// OBX_store_options with the model by calling obx_opt_model() and subsequently opening a store with obx_store_open().
/// As soon as you call obx_store_open(), the model pointer is consumed and MUST NOT be freed manually.
static inline OBX_model* create_obx_model() {
    OBX_model* model = obx_model();
    if (!model) return NULL;
    
    obx_model_entity(model, "BroadcastSettings", 1, 4983374517096241241);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 4739269246231445414);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "platform", OBXPropertyType_String, 2, 4040633880717979746);
    obx_model_property(model, "stream_key", OBXPropertyType_String, 3, 8370627668021134012);
    obx_model_property(model, "server_url", OBXPropertyType_String, 4, 4169666315763708143);
    obx_model_property(model, "bitrate", OBXPropertyType_Int, 5, 8960471891043545626);
    obx_model_property(model, "resolution", OBXPropertyType_String, 6, 9182105764800302265);
    obx_model_property(model, "framerate", OBXPropertyType_Int, 7, 3054091125498663627);
    obx_model_property(model, "encoder", OBXPropertyType_String, 8, 6340113412831970412);
    obx_model_property(model, "audio_bitrate", OBXPropertyType_Int, 9, 8130479897569182011);
    obx_model_property(model, "sample_rate", OBXPropertyType_Int, 10, 5183927744598799625);
    obx_model_property(model, "enabled", OBXPropertyType_Bool, 11, 4189994237562563643);
    obx_model_entity_last_property_id(model, 11, 4189994237562563643);
    
    obx_model_entity(model, "AnimationKeyframe", 2, 7470032134549567603);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 6830389758620302980);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "object_id", OBXPropertyType_Long, 2, 1933690219521896575);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "node_id", OBXPropertyType_String, 3, 1166423187444966949);
    obx_model_property(model, "timestamp_ms", OBXPropertyType_Date, 4, 7626816835733007624);
    obx_model_property_flags(model, OBXPropertyFlags_ID_COMPANION);
    obx_model_property(model, "pos_x", OBXPropertyType_Float, 5, 5239153353790514682);
    obx_model_property(model, "pos_y", OBXPropertyType_Float, 6, 4203417546208624027);
    obx_model_property(model, "pos_z", OBXPropertyType_Float, 7, 1764901859277132616);
    obx_model_property(model, "rot_x", OBXPropertyType_Float, 8, 7497430310142092571);
    obx_model_property(model, "rot_y", OBXPropertyType_Float, 9, 4792991999221501700);
    obx_model_property(model, "rot_z", OBXPropertyType_Float, 10, 5923910447790585973);
    obx_model_property(model, "scale_x", OBXPropertyType_Float, 11, 3069348221139012588);
    obx_model_property(model, "scale_y", OBXPropertyType_Float, 12, 1159443774650843705);
    obx_model_property(model, "scale_z", OBXPropertyType_Float, 13, 3269063388332667008);
    obx_model_property(model, "script_id", OBXPropertyType_Long, 14, 8744371900234847323);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "interpolation", OBXPropertyType_String, 15, 2327174666706499271);
    obx_model_entity_last_property_id(model, 15, 2327174666706499271);
    
    obx_model_entity(model, "SceneObject", 3, 765965672176352531);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 8298277251682432903);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "node_id", OBXPropertyType_String, 2, 8570262232547793784);
    obx_model_property(model, "type", OBXPropertyType_String, 3, 5945665489862808148);
    obx_model_property(model, "name", OBXPropertyType_String, 4, 3063893182585899335);
    obx_model_property(model, "pos_x", OBXPropertyType_Float, 5, 799715896026418397);
    obx_model_property(model, "pos_y", OBXPropertyType_Float, 6, 2908092011459023694);
    obx_model_property(model, "pos_z", OBXPropertyType_Float, 7, 4171391756888130785);
    obx_model_property(model, "rot_x", OBXPropertyType_Float, 8, 330306955504229529);
    obx_model_property(model, "rot_y", OBXPropertyType_Float, 9, 8712526186490695518);
    obx_model_property(model, "rot_z", OBXPropertyType_Float, 10, 7915708143972665323);
    obx_model_property(model, "scale_x", OBXPropertyType_Float, 11, 1370787891354403537);
    obx_model_property(model, "scale_y", OBXPropertyType_Float, 12, 6811259124074724828);
    obx_model_property(model, "scale_z", OBXPropertyType_Float, 13, 8592582243557599052);
    obx_model_property(model, "enabled", OBXPropertyType_Bool, 14, 227614118282955526);
    obx_model_property(model, "properties", OBXPropertyType_String, 15, 2825556049937191521);
    obx_model_entity_last_property_id(model, 15, 2825556049937191521);
    
    obx_model_entity(model, "NodeType", 4, 691585485205749242);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 7206512075372682825);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "name", OBXPropertyType_String, 2, 182933630801232067);
    obx_model_property(model, "category", OBXPropertyType_String, 3, 245472486318685095);
    obx_model_property(model, "display_name", OBXPropertyType_String, 4, 7302076843148902891);
    obx_model_property(model, "description", OBXPropertyType_String, 5, 2087505208827666730);
    obx_model_property(model, "icon", OBXPropertyType_String, 6, 7284051790836970057);
    obx_model_property(model, "default_config", OBXPropertyType_String, 7, 3800929147163572612);
    obx_model_property(model, "input_ports", OBXPropertyType_String, 8, 3454282178717654690);
    obx_model_property(model, "output_ports", OBXPropertyType_String, 9, 7294412781335254579);
    obx_model_property(model, "version", OBXPropertyType_Int, 10, 4185973465504983771);
    obx_model_entity_last_property_id(model, 10, 4185973465504983771);
    
    obx_model_entity(model, "ConnectionRule", 5, 2767127479057613079);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 6208786491683423225);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "from_type_id", OBXPropertyType_Long, 2, 2467527430734305151);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "to_type_id", OBXPropertyType_Long, 3, 1210422276073254018);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "from_port_name", OBXPropertyType_String, 4, 4556176520996868250);
    obx_model_property(model, "to_port_name", OBXPropertyType_String, 5, 7339147468667811917);
    obx_model_property(model, "constraints", OBXPropertyType_String, 6, 8048085061339828555);
    obx_model_entity_last_property_id(model, 6, 8048085061339828555);
    
    obx_model_entity(model, "PipelineTemplate", 6, 5035399726560040859);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 3123251284371766190);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "name", OBXPropertyType_String, 2, 205587244958340249);
    obx_model_property(model, "category", OBXPropertyType_String, 3, 2449168693765088158);
    obx_model_property(model, "description", OBXPropertyType_String, 4, 5889767807897221990);
    obx_model_property(model, "graph_json", OBXPropertyType_String, 5, 2049855418491791861);
    obx_model_property(model, "thumbnail", OBXPropertyType_String, 6, 3278812170213056336);
    obx_model_entity_last_property_id(model, 6, 3278812170213056336);
    
    obx_model_entity(model, "GraphNode", 7, 3151993038422604410);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 2506050045069201598);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "type_id", OBXPropertyType_Long, 2, 4080929898332409332);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "name", OBXPropertyType_String, 3, 6830349750384718923);
    obx_model_property(model, "pos_x", OBXPropertyType_Float, 4, 8594221677595933538);
    obx_model_property(model, "pos_y", OBXPropertyType_Float, 5, 3200720532479448638);
    obx_model_property(model, "pos_z", OBXPropertyType_Float, 6, 1795798955359061355);
    obx_model_property(model, "config_json", OBXPropertyType_String, 7, 3297562220732756698);
    obx_model_property(model, "enabled", OBXPropertyType_Bool, 8, 5380986810566331179);
    obx_model_property(model, "created_at", OBXPropertyType_Long, 9, 999710280616103365);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED);
    obx_model_property_index_id(model, 1, 5864996251858635037);
    obx_model_entity_last_property_id(model, 9, 999710280616103365);
    
    obx_model_entity(model, "GraphEdge", 8, 7988323572453525072);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 1945451722973120682);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "from_node_id", OBXPropertyType_Relation, 2, 6418131887734195272);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "GraphNode", 2, 6986325636522500868);
    obx_model_property(model, "to_node_id", OBXPropertyType_Relation, 3, 2321869519645333000);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "GraphNode", 3, 174478287737931212);
    obx_model_property(model, "from_port", OBXPropertyType_String, 4, 6738218524042367562);
    obx_model_property(model, "to_port", OBXPropertyType_String, 5, 5648578808653313273);
    obx_model_property(model, "data_type", OBXPropertyType_String, 6, 5871800209889044441);
    obx_model_property(model, "enabled", OBXPropertyType_Bool, 7, 7751187013345813373);
    obx_model_entity_last_property_id(model, 7, 7751187013345813373);
    
    obx_model_entity(model, "GraphEvent", 9, 7518635190650337221);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 6459456832930191507);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "timestamp", OBXPropertyType_Date, 2, 6120605933864547403);
    obx_model_property_flags(model, OBXPropertyFlags_ID_COMPANION);
    obx_model_property(model, "event_type", OBXPropertyType_String, 3, 1336785362253568950);
    obx_model_property(model, "node_type", OBXPropertyType_String, 4, 1483959732374349654);
    obx_model_property(model, "from_type", OBXPropertyType_String, 5, 8754286289047755458);
    obx_model_property(model, "to_type", OBXPropertyType_String, 6, 3464222242673606493);
    obx_model_property(model, "from_port", OBXPropertyType_String, 7, 8206431129058822337);
    obx_model_property(model, "to_port", OBXPropertyType_String, 8, 5755448157255162611);
    obx_model_property(model, "context_hash", OBXPropertyType_String, 9, 1500084222071228117);
    obx_model_property(model, "session_id", OBXPropertyType_String, 10, 2971015498239945990);
    obx_model_property_flags(model, OBXPropertyFlags_INDEX_HASH);
    obx_model_property_index_id(model, 4, 4743171403228677233);
    obx_model_entity_last_property_id(model, 10, 2971015498239945990);
    
    obx_model_entity(model, "GraphPattern", 10, 7684501265397504746);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 5128163235441873123);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "pattern_hash", OBXPropertyType_String, 2, 2479479140556432794);
    obx_model_property_flags(model, OBXPropertyFlags_INDEX_HASH | OBXPropertyFlags_UNIQUE);
    obx_model_property_index_id(model, 5, 3265423074363145237);
    obx_model_property(model, "node_sequence", OBXPropertyType_String, 3, 3126054317548670228);
    obx_model_property(model, "edge_structure", OBXPropertyType_String, 4, 2641872998528125278);
    obx_model_property(model, "frequency", OBXPropertyType_Long, 5, 7695267555162314596);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "success_rate", OBXPropertyType_Float, 6, 6134235376143099188);
    obx_model_property(model, "last_updated", OBXPropertyType_Long, 7, 2953916057587597850);
    obx_model_entity_last_property_id(model, 7, 2953916057587597850);
    
    obx_model_entity(model, "IntentPrediction", 11, 2230849036126152022);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 777915633890803864);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "context_hash", OBXPropertyType_String, 2, 7812563807704275353);
    obx_model_property_flags(model, OBXPropertyFlags_INDEX_HASH);
    obx_model_property_index_id(model, 6, 3957028577785953062);
    obx_model_property(model, "predicted_node_type", OBXPropertyType_String, 3, 2756926705052696206);
    obx_model_property(model, "predicted_from_type", OBXPropertyType_String, 4, 4647502309933657841);
    obx_model_property(model, "predicted_to_type", OBXPropertyType_String, 5, 6631754017620906083);
    obx_model_property(model, "confidence", OBXPropertyType_Float, 6, 7670002493036526741);
    obx_model_property(model, "reason", OBXPropertyType_String, 7, 4253613767955126374);
    obx_model_entity_last_property_id(model, 7, 4253613767955126374);
    
    obx_model_last_entity_id(model, 11, 2230849036126152022);
    obx_model_last_index_id(model, 6, 3957028577785953062);
    return model; // NOTE: the returned model will contain error information if an error occurred.
}

#ifdef __cplusplus
}
#endif
