// Code generated by ObjectBox; DO NOT EDIT.

#include "AnimationKeyframe.obx.hpp"

const obx::Property<NeuralStudio::AnimationKeyframe, OBXPropertyType_Long> NeuralStudio::AnimationKeyframe_::id(1);
const obx::Property<NeuralStudio::AnimationKeyframe, OBXPropertyType_Long> NeuralStudio::AnimationKeyframe_::object_id(2);
const obx::Property<NeuralStudio::AnimationKeyframe, OBXPropertyType_String> NeuralStudio::AnimationKeyframe_::node_id(3);
const obx::Property<NeuralStudio::AnimationKeyframe, OBXPropertyType_Date> NeuralStudio::AnimationKeyframe_::timestamp_ms(4);
const obx::Property<NeuralStudio::AnimationKeyframe, OBXPropertyType_Float> NeuralStudio::AnimationKeyframe_::pos_x(5);
const obx::Property<NeuralStudio::AnimationKeyframe, OBXPropertyType_Float> NeuralStudio::AnimationKeyframe_::pos_y(6);
const obx::Property<NeuralStudio::AnimationKeyframe, OBXPropertyType_Float> NeuralStudio::AnimationKeyframe_::pos_z(7);
const obx::Property<NeuralStudio::AnimationKeyframe, OBXPropertyType_Float> NeuralStudio::AnimationKeyframe_::rot_x(8);
const obx::Property<NeuralStudio::AnimationKeyframe, OBXPropertyType_Float> NeuralStudio::AnimationKeyframe_::rot_y(9);
const obx::Property<NeuralStudio::AnimationKeyframe, OBXPropertyType_Float> NeuralStudio::AnimationKeyframe_::rot_z(10);
const obx::Property<NeuralStudio::AnimationKeyframe, OBXPropertyType_Float> NeuralStudio::AnimationKeyframe_::scale_x(11);
const obx::Property<NeuralStudio::AnimationKeyframe, OBXPropertyType_Float> NeuralStudio::AnimationKeyframe_::scale_y(12);
const obx::Property<NeuralStudio::AnimationKeyframe, OBXPropertyType_Float> NeuralStudio::AnimationKeyframe_::scale_z(13);
const obx::Property<NeuralStudio::AnimationKeyframe, OBXPropertyType_Long> NeuralStudio::AnimationKeyframe_::script_id(14);
const obx::Property<NeuralStudio::AnimationKeyframe, OBXPropertyType_String> NeuralStudio::AnimationKeyframe_::interpolation(15);

void NeuralStudio::AnimationKeyframe::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const NeuralStudio::AnimationKeyframe& object) {
    fbb.Clear();
    auto offsetnode_id = fbb.CreateString(object.node_id);
    auto offsetinterpolation = fbb.CreateString(object.interpolation);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddElement(6, object.object_id);
    fbb.AddOffset(8, offsetnode_id);
    fbb.AddElement(10, object.timestamp_ms);
    fbb.AddElement(12, object.pos_x);
    fbb.AddElement(14, object.pos_y);
    fbb.AddElement(16, object.pos_z);
    fbb.AddElement(18, object.rot_x);
    fbb.AddElement(20, object.rot_y);
    fbb.AddElement(22, object.rot_z);
    fbb.AddElement(24, object.scale_x);
    fbb.AddElement(26, object.scale_y);
    fbb.AddElement(28, object.scale_z);
    fbb.AddElement(30, object.script_id);
    fbb.AddOffset(32, offsetinterpolation);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

NeuralStudio::AnimationKeyframe NeuralStudio::AnimationKeyframe::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    NeuralStudio::AnimationKeyframe object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<NeuralStudio::AnimationKeyframe> NeuralStudio::AnimationKeyframe::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<NeuralStudio::AnimationKeyframe>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void NeuralStudio::AnimationKeyframe::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, NeuralStudio::AnimationKeyframe& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    outObject.object_id = table->GetField<uint64_t>(6, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(8);
        if (ptr) {
            outObject.node_id.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.node_id.clear();
        }
    }
    outObject.timestamp_ms = table->GetField<int64_t>(10, 0);
    outObject.pos_x = table->GetField<float>(12, 0.0f);
    outObject.pos_y = table->GetField<float>(14, 0.0f);
    outObject.pos_z = table->GetField<float>(16, 0.0f);
    outObject.rot_x = table->GetField<float>(18, 0.0f);
    outObject.rot_y = table->GetField<float>(20, 0.0f);
    outObject.rot_z = table->GetField<float>(22, 0.0f);
    outObject.scale_x = table->GetField<float>(24, 0.0f);
    outObject.scale_y = table->GetField<float>(26, 0.0f);
    outObject.scale_z = table->GetField<float>(28, 0.0f);
    outObject.script_id = table->GetField<uint64_t>(30, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(32);
        if (ptr) {
            outObject.interpolation.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.interpolation.clear();
        }
    }
}

