// Code generated by ObjectBox; DO NOT EDIT.

#include "BroadcastSettings.obx.hpp"

const obx::Property<NeuralStudio::BroadcastSettings, OBXPropertyType_Long> NeuralStudio::BroadcastSettings_::id(1);
const obx::Property<NeuralStudio::BroadcastSettings, OBXPropertyType_String> NeuralStudio::BroadcastSettings_::platform(2);
const obx::Property<NeuralStudio::BroadcastSettings, OBXPropertyType_String> NeuralStudio::BroadcastSettings_::stream_key(3);
const obx::Property<NeuralStudio::BroadcastSettings, OBXPropertyType_String> NeuralStudio::BroadcastSettings_::server_url(4);
const obx::Property<NeuralStudio::BroadcastSettings, OBXPropertyType_Int> NeuralStudio::BroadcastSettings_::bitrate(5);
const obx::Property<NeuralStudio::BroadcastSettings, OBXPropertyType_String> NeuralStudio::BroadcastSettings_::resolution(6);
const obx::Property<NeuralStudio::BroadcastSettings, OBXPropertyType_Int> NeuralStudio::BroadcastSettings_::framerate(7);
const obx::Property<NeuralStudio::BroadcastSettings, OBXPropertyType_String> NeuralStudio::BroadcastSettings_::encoder(8);
const obx::Property<NeuralStudio::BroadcastSettings, OBXPropertyType_Int> NeuralStudio::BroadcastSettings_::audio_bitrate(9);
const obx::Property<NeuralStudio::BroadcastSettings, OBXPropertyType_Int> NeuralStudio::BroadcastSettings_::sample_rate(10);
const obx::Property<NeuralStudio::BroadcastSettings, OBXPropertyType_Bool> NeuralStudio::BroadcastSettings_::enabled(11);

void NeuralStudio::BroadcastSettings::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const NeuralStudio::BroadcastSettings& object) {
    fbb.Clear();
    auto offsetplatform = fbb.CreateString(object.platform);
    auto offsetstream_key = fbb.CreateString(object.stream_key);
    auto offsetserver_url = fbb.CreateString(object.server_url);
    auto offsetresolution = fbb.CreateString(object.resolution);
    auto offsetencoder = fbb.CreateString(object.encoder);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddOffset(6, offsetplatform);
    fbb.AddOffset(8, offsetstream_key);
    fbb.AddOffset(10, offsetserver_url);
    fbb.AddElement(12, object.bitrate);
    fbb.AddOffset(14, offsetresolution);
    fbb.AddElement(16, object.framerate);
    fbb.AddOffset(18, offsetencoder);
    fbb.AddElement(20, object.audio_bitrate);
    fbb.AddElement(22, object.sample_rate);
    fbb.AddElement(24, object.enabled ? 1 : 0);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

NeuralStudio::BroadcastSettings NeuralStudio::BroadcastSettings::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    NeuralStudio::BroadcastSettings object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<NeuralStudio::BroadcastSettings> NeuralStudio::BroadcastSettings::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<NeuralStudio::BroadcastSettings>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void NeuralStudio::BroadcastSettings::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, NeuralStudio::BroadcastSettings& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(6);
        if (ptr) {
            outObject.platform.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.platform.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(8);
        if (ptr) {
            outObject.stream_key.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.stream_key.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(10);
        if (ptr) {
            outObject.server_url.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.server_url.clear();
        }
    }
    outObject.bitrate = table->GetField<int32_t>(12, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(14);
        if (ptr) {
            outObject.resolution.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.resolution.clear();
        }
    }
    outObject.framerate = table->GetField<int32_t>(16, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(18);
        if (ptr) {
            outObject.encoder.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.encoder.clear();
        }
    }
    outObject.audio_bitrate = table->GetField<int32_t>(20, 0);
    outObject.sample_rate = table->GetField<int32_t>(22, 0);
    outObject.enabled = table->GetField<uint8_t>(24, 0) != 0;
}

