// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#ifdef __cplusplus
#include <cstdbool>
#include <cstdint>
extern "C" {
#else
#include <stdbool.h>
#include <stdint.h>
#endif
#include "objectbox.h"

/// Initializes an ObjectBox model for all entities. 
/// The returned pointer may be NULL if the allocation failed. If the returned model is not NULL, you should check if   
/// any error occurred by calling obx_model_error_code() and/or obx_model_error_message(). If an error occurred, you're
/// responsible for freeing the resources by calling obx_model_free().
/// In case there was no error when setting the model up (i.e. obx_model_error_code() returned 0), you may configure 
/// OBX_store_options with the model by calling obx_opt_model() and subsequently opening a store with obx_store_open().
/// As soon as you call obx_store_open(), the model pointer is consumed and MUST NOT be freed manually.
static inline OBX_model* create_obx_model() {
    OBX_model* model = obx_model();
    if (!model) return NULL;
    
    obx_model_entity(model, "BroadcastSettings", 1, 4983374517096241241);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 4739269246231445414);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "platform", OBXPropertyType_String, 2, 4040633880717979746);
    obx_model_property(model, "stream_key", OBXPropertyType_String, 3, 8370627668021134012);
    obx_model_property(model, "server_url", OBXPropertyType_String, 4, 4169666315763708143);
    obx_model_property(model, "bitrate", OBXPropertyType_Int, 5, 8960471891043545626);
    obx_model_property(model, "resolution", OBXPropertyType_String, 6, 9182105764800302265);
    obx_model_property(model, "framerate", OBXPropertyType_Int, 7, 3054091125498663627);
    obx_model_property(model, "encoder", OBXPropertyType_String, 8, 6340113412831970412);
    obx_model_property(model, "audio_bitrate", OBXPropertyType_Int, 9, 8130479897569182011);
    obx_model_property(model, "sample_rate", OBXPropertyType_Int, 10, 5183927744598799625);
    obx_model_property(model, "enabled", OBXPropertyType_Bool, 11, 4189994237562563643);
    obx_model_entity_last_property_id(model, 11, 4189994237562563643);
    
    obx_model_entity(model, "AnimationKeyframe", 2, 7470032134549567603);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 6830389758620302980);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "object_id", OBXPropertyType_Long, 2, 1933690219521896575);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "node_id", OBXPropertyType_String, 3, 1166423187444966949);
    obx_model_property(model, "timestamp_ms", OBXPropertyType_Date, 4, 7626816835733007624);
    obx_model_property_flags(model, OBXPropertyFlags_ID_COMPANION);
    obx_model_property(model, "pos_x", OBXPropertyType_Float, 5, 5239153353790514682);
    obx_model_property(model, "pos_y", OBXPropertyType_Float, 6, 4203417546208624027);
    obx_model_property(model, "pos_z", OBXPropertyType_Float, 7, 1764901859277132616);
    obx_model_property(model, "rot_x", OBXPropertyType_Float, 8, 7497430310142092571);
    obx_model_property(model, "rot_y", OBXPropertyType_Float, 9, 4792991999221501700);
    obx_model_property(model, "rot_z", OBXPropertyType_Float, 10, 5923910447790585973);
    obx_model_property(model, "scale_x", OBXPropertyType_Float, 11, 3069348221139012588);
    obx_model_property(model, "scale_y", OBXPropertyType_Float, 12, 1159443774650843705);
    obx_model_property(model, "scale_z", OBXPropertyType_Float, 13, 3269063388332667008);
    obx_model_property(model, "script_id", OBXPropertyType_Long, 14, 8744371900234847323);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "interpolation", OBXPropertyType_String, 15, 2327174666706499271);
    obx_model_entity_last_property_id(model, 15, 2327174666706499271);
    
    obx_model_entity(model, "SceneObject", 3, 765965672176352531);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 8298277251682432903);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "node_id", OBXPropertyType_String, 2, 8570262232547793784);
    obx_model_property(model, "type", OBXPropertyType_String, 3, 5945665489862808148);
    obx_model_property(model, "name", OBXPropertyType_String, 4, 3063893182585899335);
    obx_model_property(model, "pos_x", OBXPropertyType_Float, 5, 799715896026418397);
    obx_model_property(model, "pos_y", OBXPropertyType_Float, 6, 2908092011459023694);
    obx_model_property(model, "pos_z", OBXPropertyType_Float, 7, 4171391756888130785);
    obx_model_property(model, "rot_x", OBXPropertyType_Float, 8, 330306955504229529);
    obx_model_property(model, "rot_y", OBXPropertyType_Float, 9, 8712526186490695518);
    obx_model_property(model, "rot_z", OBXPropertyType_Float, 10, 7915708143972665323);
    obx_model_property(model, "scale_x", OBXPropertyType_Float, 11, 1370787891354403537);
    obx_model_property(model, "scale_y", OBXPropertyType_Float, 12, 6811259124074724828);
    obx_model_property(model, "scale_z", OBXPropertyType_Float, 13, 8592582243557599052);
    obx_model_property(model, "enabled", OBXPropertyType_Bool, 14, 227614118282955526);
    obx_model_property(model, "properties", OBXPropertyType_String, 15, 2825556049937191521);
    obx_model_entity_last_property_id(model, 15, 2825556049937191521);
    
    obx_model_last_entity_id(model, 3, 765965672176352531);
    return model; // NOTE: the returned model will contain error information if an error occurred.
}

#ifdef __cplusplus
}
#endif
