// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#include <cstdbool>
#include <cstdint>

#include "flatbuffers/flatbuffers.h"
#include "objectbox.h"
#include "objectbox.hpp"


namespace NeuralStudio {
struct SceneObject_;

struct SceneObject {
    obx_id id;
    std::string node_id;
    std::string type;
    std::string name;
    float pos_x;
    float pos_y;
    float pos_z;
    float rot_x;
    float rot_y;
    float rot_z;
    float scale_x;
    float scale_y;
    float scale_z;
    bool enabled;
    std::string properties;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 3; }
    
        static void setObjectId(SceneObject& object, obx_id newId) { object.id = newId; }
    
        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const SceneObject& object);
    
        /// Read an object from a valid FlatBuffer
        static SceneObject fromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<SceneObject> newFromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, SceneObject& outObject);
    };
};

struct SceneObject_ {
    static const obx::Property<SceneObject, OBXPropertyType_Long> id;
    static const obx::Property<SceneObject, OBXPropertyType_String> node_id;
    static const obx::Property<SceneObject, OBXPropertyType_String> type;
    static const obx::Property<SceneObject, OBXPropertyType_String> name;
    static const obx::Property<SceneObject, OBXPropertyType_Float> pos_x;
    static const obx::Property<SceneObject, OBXPropertyType_Float> pos_y;
    static const obx::Property<SceneObject, OBXPropertyType_Float> pos_z;
    static const obx::Property<SceneObject, OBXPropertyType_Float> rot_x;
    static const obx::Property<SceneObject, OBXPropertyType_Float> rot_y;
    static const obx::Property<SceneObject, OBXPropertyType_Float> rot_z;
    static const obx::Property<SceneObject, OBXPropertyType_Float> scale_x;
    static const obx::Property<SceneObject, OBXPropertyType_Float> scale_y;
    static const obx::Property<SceneObject, OBXPropertyType_Float> scale_z;
    static const obx::Property<SceneObject, OBXPropertyType_Bool> enabled;
    static const obx::Property<SceneObject, OBXPropertyType_String> properties;
};
}  // namespace NeuralStudio

